### ISSUE TITLE
Can only --find coins in top 10

### ISSUE THREAD

**Issue by polyzen** [RDCH106/pycoinmon#8]
Attempt to find many coins at once: http://pb.gehidore.net/Uzax.png
Test to make sure output with `-f` isn't just limited to 10 coins: http://pb.gehidore.net/Aqbj.png

`-t` with an index greater than 10 works as expected, so there's that.

Python 3.6.4
colorama 0.3.9
humanize 0.5.1
requests 2.18.4
tabulate 0.8.2

**Comment by RDCH106** [comment]
Yes @polyzen that is!!

The param `--find` operates inside the results defined by `--top` param. By default the value of `--top` is 10.

`--top` or `-t` operates in the same way as limit in SQL languages. The reason is to handle as little data traffic as possible.

So the behaviour is as expected. Try increase `--top` param with the value that you need.
